spring.application.name=dynalar

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://kc1y-u.h.filess.io:3307/dynalar_citywelldo
spring.datasource.username=dynalar_citywelldo
spring.datasource.password=f53426becb0aa1d0b00504102ff97959825322bb

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
