spring.application.name=dynalar

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://qhax3q.h.filess.io:3307/dynalar_originalme
spring.datasource.username=dynalar_originalme
spring.datasource.password=d89d8be7d816e11ea10bbfc14732bdb56dbf2ad7

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
